export const CHOOSE_FROM_DROPDOWN = 'CHOOSE_FROM_DROPDOWN';
export const UPDATE_ARRAY_OF_CELLS = 'UPDATE_ARRAY_OF_CELLS';
export const UPDATE_ZOOM = 'UPDATE_ZOOM';
export const UPDATE_MAP_INTERACTION_CSS = 'UPDATE_MAP_INTERACTION_CSS';
export const START_ZOOMING = 'START_ZOOMING';
export const GAME_INITIALIZATION = 'GAME_INITIALIZATION';
export const MAKE_THE_CELL_ALIVE = 'MAKE_THE_CELL_ALIVE';

