export const CHOOSE_FROM_DROPDOWN = 'CHOOSE_FROM_DROPDOWN';
export const UPDATE_NUMBER_OF_CELLS = 'UPDATE_NUMBER_OF_CELLS';
export const UPDATE_ZOOM = 'UPDATE_ZOOM';
export const UPDATE_MAP_INTERACTION_CSS = 'UPDATE_MAP_INTERACTION_CSS';
export const START_ZOOMING = 'START_ZOOMING';
